---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit-backend
  namespace: conduit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conduit-backend
  template:
    metadata:
      name: conduit-backend
      labels:
        app: conduit-backend
    spec:
      containers:
      - name: conduit-backend
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-initcreds
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-initcreds
              key: password
        - name: DATABASE_HOSTNAME
          value: database-rw
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: app
        image: jakobyte1024/conduit-backend:sha-8094fe2
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: conduit-backend
  namespace: conduit-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: conduit-backend
---
