---
apiVersion: v1
kind: Namespace
metadata:
  name: conduit

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit-backend
  namespace: conduit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conduit-backend
  template:
    metadata:
      name: conduit-backend
      labels:
        app: conduit-backend
    spec:
      containers:
      - name: conduit-backend
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: databaseUser
          valueFrom:
            secretKeyRef:
              name: conduit-db-app
              key: username
        - name: databasePassword
          valueFrom:
            secretKeyRef:
              name: conduit-db-app
              key: password
        - name: databaseHost
          value: conduit-db
        image: jakobyte1024/conduit-backend:main
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: conduit-backend
  namespace: conduit
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: conduit-backend
---